--- #YAML:1.0
name:         ExtUtils-Manifest
version:      1.58
version_from: lib/ExtUtils/Manifest.pm
installdirs:  perl
license:      perl
abstract:     utilities to write and check a MANIFEST file
authored_by:
    - Randy Kobes <randy.kobes@gmail.com>
requires:
    File::Basename:                0
    File::Spec:                    0.8
provides:
  ExtUtils::Manifest:
    file: lib/ExtUtils/Manifest.pm
    version: 1.58
distribution_type: module
generated_by: Randy Kobes
urls:
   license: http://dev.perl.org/licenses/
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://github.com/rkobes/extutils-manifest
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=ExtUtils-Manifest
  AnnoCPAN: http://annocpan.org/dist/ExtUtils-Manifest
  CPANForum: http://www.cpanforum.com/dist/ExtUtils-Manifest
  CPANTS: http://cpants.perl.org/dist/ExtUtils-Manifest
  Rating: http://cpanratings.perl.org/d/ExtUtils-Manifest
  SearchCPAN: http://search.cpan.org/~RKOBES/ExtUtils-Manifest/
  Testers: http://cpantesters.perl.org/show/ExtUtils-Manifest.html
  UWinnipeg: http://cpan.uwinnipeg.ca/dist/ExtUtils-Manifest
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
